# Permalinks
permalink:           pretty

# Setup
title:               So long, and thanks for all the bits
tagline:             an engineering blog
url:                 https://jamejone.github.io/
paginate:            1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              James Jones
  url:               https://twitter.com/james_output
  email:             james.russel.jones@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/jamejone/jamejone.github.io/

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
